#  2018 yılında geçen araçlar

In [11]:
import pandas as pd

yol='C:\\Users\\mertoglue\\AnacondaProjects\\CSV\\plakaOlustur\\giden.csv'
        
veri = pd.read_csv(yol, encoding = "ISO-8859-1" ,sep=',')   # pandas ile dosya okunup veriler alınıyor ve okunan veriler, veri değişkenine atanıyor

filtre=veri[(veri['yil']==2018)]

filtre

        plaka  dakika  saat  gun  ay   yil  skod
2     43ZL681      38     9   28   4  2018    43
3    38PFL195      51    22   13  10  2018    38
5     25UH929      12     2   24  10  2018    25
6     24CEB59       8    15   11   3  2018    24
7      67HA10      54     2   21   5  2018    67
10    75USD34      17    15   15   2  2018    75
17    28PG524       5    15    2   4  2018    28
18   10MHU726      56    22   24   7  2018    10
21    64RV417      20     8   21   7  2018    64
27     74BC37      32    12    4   4  2018    74
35    67TN388      29    17   18  12  2018    67
38    57TK758      56     8    7   5  2018    57
48    21RK606      59    22   24   5  2018    21
50   68KPR937      53    16   16   4  2018    68
51    27MZ271      15    15    9  11  2018    27
55    34HT824      51    22   12   9  2018    34
56    57FZ535      24     5   26   2  2018    57
65    46HK609      43    21    6  11  2018    46
71    40KO297      60    12   13   3  2018    40
77   48YNS231      19    14    9  10  2018    48
78   62BHI803      22     1   21  10  2018    62
84    61OT545      35     6   20   5  2018    61
90    35BI642      42    23   27  12  2018    35
93   74BST296      52     8   29   6  2018    74
94   65SCE780       1    13   25  11  2018    65
95   32PGZ381       4     2    4  10  2018    32
104  40NMI168      10    19   10  10  2018    40
118   68YD968      38    16   13   9  2018    68
119  17HCB930      32     3   17   9  2018    17
120   54GI940       8    18    8   5  2018    54
..        ...     ...   ...  ...  ..   ...   ...
369  55ZYD191      46    19   24   3  2018    55
377   63FU854      19    14    8  11  2018    63
380  15BVI226      27     2   30   6  2018    15
381   67VS403      60    23   14  12  2018    67
392   69MI308       6    22   26  12  2018    69
400  47OZP819      42    24   14   1  2018    47
401   53VU753      54     4   17  10  2018    53
403    67AZ22      43    10   16   5  2018    67
405  34JNA216      14    20   19   9  2018    34
406   73NBV66      32     9   13   8  2018    73
410  77JZU932      39    13    2   1  2018    77
412    15MV47      21     4    7   7  2018    15
415  35IGB656      16    15    6   7  2018    35
420   79RN136       6    23   18   6  2018    79
422  20FMT635      27    23   21   9  2018    20
423    52VT38      47    16   30  12  2018    52
435   65HB923      40    12    9  10  2018    65
444   74CZ588      59     7    4   6  2018    74
447   21EL662      31    11    4   2  2018    21
449  17DRM193      24     3   21  12  2018    17
451   29RM798      47    18   27   2  2018    29
471   37MJ523       9    18   21   5  2018    37
474  49EHG126      35     8   20   5  2018    49
475  24HNA991      15     5    6   1  2018    24
476  75SRV973       2    14    8  10  2018    75
481  21UFM492      23     2   14  11  2018    21
487   10FT209      20    10    1  12  2018    10
491  37AKE340      44    10   15   6  2018    37
492  22GPU681      16     5    3   6  2018    22
499    68LI89      53     6   26   9  2018    68

[114 rows x 7 columns]

# 2018 yılında geçen araçların SAYISI

In [16]:
import pandas as pd

yol='C:\\Users\\mertoglue\\AnacondaProjects\\CSV\\plakaOlustur\\giden.csv'
        
veri = pd.read_csv(yol, encoding = "ISO-8859-1" ,sep=',')   # pandas ile dosya okunup veriler alınıyor ve okunan veriler, veri değişkenine atanıyor

filtre=veri[(veri['yil']==2018)].count()[0]

filtre

114

# Herhangi bir yılın Mayıs ayında geçen araçlar

In [18]:
import pandas as pd

yol='C:\\Users\\mertoglue\\AnacondaProjects\\CSV\\plakaOlustur\\giden.csv'
        
veri = pd.read_csv(yol, encoding = "ISO-8859-1" ,sep=',')   # pandas ile dosya okunup veriler alınıyor ve okunan veriler, veri değişkenine atanıyor

filtre=veri[(veri['ay']==5)]
#filtre=veri[(veri['ay']==5)].count()[0]      # Kaç tane oldukları
filtre

41

# İstanbul Plakalı olup gelen araçlar

In [20]:
import pandas as pd

yol='C:\\Users\\mertoglue\\AnacondaProjects\\CSV\\plakaOlustur\\giden.csv'
        
veri = pd.read_csv(yol, encoding = "ISO-8859-1" ,sep=',')   # pandas ile dosya okunup veriler alınıyor ve okunan veriler, veri değişkenine atanıyor

filtre=veri[(veri['skod']==34)]

filtre

        plaka  dakika  saat  gun  ay   yil  skod
44   34GSK470      10    16   12  11  2015    34
55    34HT824      51    22   12   9  2018    34
103  34RCL491      53    11   20   9  2017    34
145   34VS651      38    18    4   6  2016    34
188  34TVE395      37     1   26  11  2015    34
267   34NE695      19    13   13   8  2018    34
304  34DNC249      45    18    6   9  2016    34
370   34GZB46       3     7   26  11  2016    34
405  34JNA216      14    20   19   9  2018    34
468   34AM738      39    15   20   6  2015    34

# Ankara Plakalı olup gelen araçlar

In [22]:
import pandas as pd

yol='C:\\Users\\mertoglue\\AnacondaProjects\\CSV\\plakaOlustur\\giden.csv'
        
veri = pd.read_csv(yol, encoding = "ISO-8859-1" ,sep=',')   # pandas ile dosya okunup veriler alınıyor ve okunan veriler, veri değişkenine atanıyor

filtre=veri[(veri['skod']==6)]

filtre

        plaka  dakika  saat  gun  ay   yil  skod
82    06IZ536       9    11   13   9  2016     6
114   06IL237       3    20    5   7  2017     6
246  06PCL720      50     8    5   3  2015     6
284   06RO918      47    16   14   1  2016     6

# 2018 ve öncesinde 5. ayda geçen araçlar

In [23]:
import pandas as pd

yol='C:\\Users\\mertoglue\\AnacondaProjects\\CSV\\plakaOlustur\\giden.csv'
        
veri = pd.read_csv(yol, encoding = "ISO-8859-1" ,sep=',')   # pandas ile dosya okunup veriler alınıyor ve okunan veriler, veri değişkenine atanıyor

filtre=veri[(veri['yil']<=2018) & (veri['ay']==5)]

filtre

        plaka  dakika  saat  gun  ay   yil  skod
7      67HA10      54     2   21   5  2018    67
38    57TK758      56     8    7   5  2018    57
48    21RK606      59    22   24   5  2018    21
57    38FG461      14    22   11   5  2016    38
81    53YH401      29    15   19   5  2015    53
84    61OT545      35     6   20   5  2018    61
101   39GB315      22    13    1   5  2017    39
106   51RB128      60     7   22   5  2015    51
113  55GVD334      50    19    8   5  2015    55
120   54GI940       8    18    8   5  2018    54
122  31GML173      37    20   15   5  2016    31
124  35SRF840      21     2   13   5  2015    35
127  44ITF870       6    13   26   5  2018    44
130   13VAS32      30    13   19   5  2015    13
131   47NZ834      46    23   26   5  2016    47
154   26LT988      50    11    6   5  2016    26
169   23GB964      23    16   20   5  2016    23
187  10ADT869       9     1   14   5  2017    10
203   44PO201      28    18   12   5  2017    44
214  36JMH743      48    12   15   5  2015    36
223   32RY472      40    22   27   5  2015    32
230  43YIT581      47    11    3   5  2015    43
237   19TK649      53    22   15   5  2015    19
268   26FO954      59     9    1   5  2018    26
280   22DC448      43    21   30   5  2015    22
313   07CYM95       9    12   26   5  2017     7
344   46HY135      30    20    1   5  2017    46
350  57ZSM835      37    13   27   5  2016    57
359   47NP759      55    24   23   5  2018    47
365   11HC840      16     9    3   5  2017    11
371   20TUD65      59     6   25   5  2016    20
394  50CBF508      47     1   21   5  2015    50
403    67AZ22      43    10   16   5  2018    67
404   10TC888      53    12   15   5  2016    10
416  55TKL628      48    14   22   5  2017    55
453   45KI906       1    24   10   5  2016    45
463  33OIR206      47    12    7   5  2015    33
471   37MJ523       9    18   21   5  2018    37
474  49EHG126      35     8   20   5  2018    49
485    43LU71      24     2   14   5  2015    43
498  14STV293      10     4   30   5  2016    14

# 2018 ve öncesinde 9. ayda plakası 34 olan(İstanbul ili) geçen araçlar

In [28]:
import pandas as pd

# yol='C:\\Users\\mertoglue\\AnacondaProjects\\CSV\\analiz\\olustur.csv'
yol='C:\\Users\\mertoglue\\AnacondaProjects\\CSV\\plakaOlustur\\giden.csv'
        
veri = pd.read_csv(yol, encoding = "ISO-8859-1" ,sep=',')   # pandas ile dosya okunup veriler alınıyor ve okunan veriler, veri değişkenine atanıyor

filtre=veri[(veri['yil']<=2018) & (veri['ay']==9) & (veri['skod']==34) ]

filtre

        plaka  dakika  saat  gun  ay   yil  skod
55    34HT824      51    22   12   9  2018    34
103  34RCL491      53    11   20   9  2017    34
304  34DNC249      45    18    6   9  2016    34
405  34JNA216      14    20   19   9  2018    34